### ISSUE TITLE
[BUG] 当使用这个 zonemod 对抗时，舌头拉空会导致 15 秒的 cd

### ISSUE THREAD

**Issue by poplpr** [fantasylidong/L4D2-Competitive-Rework#100]
今天玩一个我的基于本 git 仓库搭建的 zonemod 插件服务器时（没有 sql 的版本），舌头只要拉空就有接近 15 秒的 cd（正常这个应该是 3 秒左右），请问一下这个是 zonemod 的设置还是您这里出了 bug 还是我不小心改坏了？（我完全没修改过 smoker 部分）T.T

然后想去别的基于您的仓库搭的服务器测试一下，发现不知道怎么单人跳过 ready 插件只能作罢。麻烦您看一下别的服是否有类似的问题，感激不尽。

**Comment by poplpr** [comment]
简单查了一下，控制这个问题的命令是 `tongue_miss_delay`，在对抗插件中没有找到相应的命令，它们使用了战役的默认时长 15 秒，具体为什么采用战役的默认时间原因不明。

我的解决方法是在 `cfg/cfgogl/zonemod/shared_cvars.cfg` 第 103 行新加一行
```
confogl_addcvar tongue_miss_delay 3                                 // 非常奇怪的问题，舌头拉空会导致 15 秒的硬直，这里强行加一个命令指定一下
```

非常奇怪的问题，不知道为什么会触发。

**Comment by poplpr** [comment]
这个解决方法感觉有点不太妙，还是麻烦您找一下为啥会触发这个bug 0.0

**Comment by fantasylidong** [comment]
具体我要看一下，前两天没时间，你这个办法暂时是有用的

**Comment by fantasylidong** [comment]
https://github.com/fantasylidong/CompetitiveWithAnne/commit/38949a35b9788ce3088914ff1b9cfcfd740531dd
已修复

**Comment by fantasylidong** [comment]
https://github.com/fantasylidong/CompetitiveWithAnne/commit/515740ea4547eb9878c746e22dc74e9e1cb6f8dd
原来那个还有点问题
