### ISSUE TITLE
[BUG] 无 sql 版本 jockey 控制的生还者出现了挣扎现象

### ISSUE THREAD

**Issue by poplpr** [fantasylidong/L4D2-Competitive-Rework#105]
今天玩一个我的基于本 git 仓库搭建的 zonemod 插件服务器时（没有 sql 的版本），jockey骑人的时候出现了明显的挣扎现象（导致我没能挂边成功），请问一下这个是 zonemod 的设置还是您这里出了 bug 还是我不小心改坏了？（我完全没修改过 jockey部分）T.T

然后想去别的基于您的仓库搭的服务器测试一下，发现不知道怎么单人跳过 ready 插件只能作罢。麻烦您看一下别的服是否有类似的问题，感激不尽。

**Comment by fantasylidong** [comment]
有视频吗，我玩对抗很少，没办法理解。

**Comment by poplpr** [comment]
这个视频里我控制 jockey 套生还者是一直按住 W 没有松开的，你可以注意到在中间出现了明显的停顿，即 jockey 套中人时生还可以挣扎以小幅度改变方向。
https://www.bilibili.com/video/BV1oJ4m1e7Fw/

**Comment by poplpr** [comment]
> 有视频吗，我玩对抗很少，没办法理解。

这个视频里我控制 jockey 套生还者是一直按住 W 没有松开的，你可以注意到在中间出现了明显的停顿，即 jockey 套中人时生还可以挣扎以小幅度改变方向。
https://www.bilibili.com/video/BV1oJ4m1e7Fw/

**Comment by poplpr** [comment]
这个视频里的插件是我自改的 zonemod 包抗插件，昨天测了 zonemod 也一样有这个问题。视频忘了切换插件了

**Comment by poplpr** [comment]
仔细研究了一天，原因可能是控AI会出现挣扎现象，但是玩家做生还则无法小范围移动。可以参见这个视频看一下观察到的现象 [为什么要在取消挣扎猴子的药抗插件里压住反方向键？（Jockey控人测试2）](https://www.bilibili.com/video/BV1Px42127Xi)

新的问题出现了，这个压速是正常现象吗 T.T

**Comment by poplpr** [comment]
以及另一个问题：AI能小范围挣扎是正常现象吗T.T

**Comment by fantasylidong** [comment]
你可以自己测试一下，我都没怎么发玩过对抗

**Comment by fantasylidong** [comment]
> 你可以自己测试一下，我都没怎么发玩过对抗

纯净对抗，纯净zonemod和我的

**Comment by fantasylidong** [comment]
游戏机制
