### ISSUE TITLE
[BUG]准备插件的BUG

### ISSUE THREAD

**Issue by keqingyyds** [fantasylidong/L4D2-Competitive-Rework#113]
不知道是我的问题还是插件包问题，之前用过一次没有问题
这次安装插件包以后，药抗的准备插件只有第一次会把人拉回安全屋，第二次就不会了
还会有AI特感生成。

**Comment by fantasylidong** [comment]
刚刚检查了一下，你把rpg插件删除一下试试看

**Comment by keqingyyds** [comment]
> 刚刚检查了一下，你把rpg插件删除一下试试看

确实如此

**Comment by fantasylidong** [comment]
> > 刚刚检查了一下，你把rpg插件删除一下试试看
> 
> 确实如此

明天我修复一下

**Comment by keqingyyds** [comment]
> Reference in new issue



> > > 刚刚检查了一下，你把rpg插件删除一下试试看
> > 
> > 
> > 确实如此
> 
> 明天我修复一下

大佬啥时候有空呢 这几天都在等着

**Comment by fantasylidong** [comment]
86329f238ee9cbb7bb23a6848d1ecdc0f9d17589 应该解决了，麻烦测试后反馈一下，谢谢

**Comment by keqingyyds** [comment]
> [86329f2](https://github.com/fantasylidong/CompetitiveWithAnne/commit/86329f238ee9cbb7bb23a6848d1ecdc0f9d17589) 应该解决了，麻烦测试后反馈一下，谢谢

还是一样

**Comment by fantasylidong** [comment]
测试已解决

**Comment by fantasylidong** [comment]
https://github.com/fantasylidong/CompetitiveWithAnne/commit/8cdf53a8bbe7ca56504b726e66f4d0aeb99b10db
