### ISSUE TITLE
【内容BUG】在被递药的同时，使用了快捷购药指令，导致被卡掉一个药

### ISSUE THREAD

**Issue by Agnes4m** [fantasylidong/L4D2-Competitive-Rework#45]
打的比较嗨忘了截图，使用指令`!pill`时候，队友已经做出了递药的动作同时药还没有到手上。结束的时候，b数被扣除，队友的药没有返回，自己身上只有一瓶药。

**Comment by fantasylidong** [comment]
确实不会返回，但是一般在脚下，相当于挤出去了，pill命令不会检测自己身上有没有药，不知道队友用的右键给还是r键用了插件功能，今天待会测试一下
