### ISSUE TITLE
[BUG]药抗模式有医疗包，药役模式正常

### ISSUE THREAD

**Issue by keqingyyds** [fantasylidong/L4D2-Competitive-Rework#64]
[BUG]药抗模式有医疗包，药役模式正常，表现为C1M2枪店四个医疗包，C2M5舞台四个包，还有很多地方都有，药役模式全程没有包

**Comment by keqingyyds** [comment]
安全屋是没有东西的，出门以后能找到包，图一个是药抗一个是药役，没有动过插件包的配置
![QQ图片20230713150548](https://github.com/fantasylidong/CompetitiveWithAnne/assets/105032048/7621a228-5cb2-4284-a8f1-bc69b42835b1)
![QQ图片20230713150553](https://github.com/fantasylidong/CompetitiveWithAnne/assets/105032048/8c5cdffe-b318-4f11-b6e8-fbac79282825)

**Comment by fantasylidong** [comment]
这个是confoglcompmod这个插件有问题，按道理这个插件的源码是能够正常删除的，但是好像编译平台不同会产生问题，我因为改过这个插件的汉化，后面怎么编译也不能正确删除，然后就不处理了。
这有两个处理办法，加载我为防止这个问题在anne写了个插件，remove.smx这个插件，来删除路途的包，写的有点久忘记能不能适配药抗的所有功能。2就是把官方项目的这个插件直接复制过来看行不行
PS: 第一个后面我还是默认加载吧，我以前也有被反馈这个问题，当前我只在anne相关模式加载了这个插件

**Comment by keqingyyds** [comment]
> 这个是confoglcompmod这个插件有问题，按道理这个插件的源码是能够正常删除的，但是好像编译平台不同会产生问题，我因为改过这个插件的汉化，后面怎么编译也不能正确删除，然后就不处理了。 这有两个处理办法，加载我为防止这个问题在anne写了个插件，removeorreplace啥的，写的有点久忘记能不能适配药抗的所有功能。2就是把官方项目的这个插件直接复制过来看行不行

肺组织

> 这个是confoglcompmod这个插件有问题，按道理这个插件的源码是能够正常删除的，但是好像编译平台不同会产生问题，我因为改过这个插件的汉化，后面怎么编译也不能正确删除，然后就不处理了。 这有两个处理办法，加载我为防止这个问题在anne写了个插件，remove.smx这个插件，来删除路途的包，写的有点久忘记能不能适配药抗的所有功能。2就是把官方项目的这个插件直接复制过来看行不行 PS: 第一个后面我还是默认加载吧，我以前也有被反馈这个问题，当前我只在anne相关模式加载了这个插件

还有一个不知道算不算bug的BUG，我删除了自带的tick解锁及L4D2toolz也无法安装https://kgithub.com/lakwsh/l4dtoolz的toolz，启动服务器提示文件丢失no such file or directory.

**Comment by fantasylidong** [comment]
不清楚，但是应该是可以兼容的。

**Comment by keqingyyds** [comment]
> 不清楚，但是应该是可以兼容的。
之前装的确实可以兼容，但是现在又不行了
