### ISSUE TITLE
[Request] AllCharger配置娱乐性更改

### ISSUE THREAD

**Issue by blueblur0730** [fantasylidong/L4D2-Competitive-Rework#70]
- 将刀对牛的伤害提至600 (即一刀必秒)
- 取消tank生成

confogl_addcvar l4d2_melee_damage_charger 600.0 (shared_settings.cfg)
confogl_addcvar sm_tank_can_spawn 0 (allcharger.cfg)

主要是和朋友这样玩了以后感觉特别的欢乐, 希望能将这个改动提交issue上去 :d

**Comment by fantasylidong** [comment]
可以考虑，我得把这个这些模式的特感击杀分数关了先

**Comment by fantasylidong** [comment]
commit a213d9a20272cac3c8ecc988dbe637e19fe817b8
done!
