### ISSUE TITLE
[BUG]AnneHappy/IncapSpawnWitch.sp 为服务器功能插件 与源码文件名不符

### ISSUE THREAD

**Issue by apples1949** [fantasylidong/L4D2-Competitive-Rework#71]
https://github.com/fantasylidong/CompetitiveWithAnne/blob/master/addons/sourcemod/scripting/AnneHappy/IncapSpawnWitch.sp
为服务器功能插件 与源码文件名不符

**Comment by apples1949** [comment]
你其他仓库好像也对不上

**Comment by fantasylidong** [comment]
我找找还有没有备份，没有的话反编译一份，我记得很简单的，就几十行

**Comment by fantasylidong** [comment]
commit: 2f7cc07ed126280bcaab0ce7f877d314ec1697a9
已修改
